### PR TITLE
Splitting person records

### PR DESCRIPTION
**Pull request by jedwardwalters**
These are person records that were split before the SBD/Qadishe volumes
went live, but for some reason they never made it from the Dev branch
to the Master.

So, now I am manually bringing over the affected files from that failed
merge into the Master.

### CODE REVIEW

**Comment by jedwardwalters** [comment]
Hey @nathangibson, here is the pull request for the those split record files. I checked the differences, and everything seems okay to me. But I'm nervous about pulling the trigger on merging before someone else has a chance to double check. Would you mind scanning through the differences just to make sure I'm not unwittingly committing some major blunder?

**Comment by nathangibson** [comment]
@jedwardwalters Mostly looks good to me. 
I noticed a few small typos and corrected some of them. I'll leave the rest to you:
- In 3142 it looks like some of the names are not fully split.
- Is 3146 name 5 supposed to be "Valens"?
- 3148 and 3149 have an extra space in the record title.
- Should attestation for 3152 say "Anonymous 3152" instead of "An Egyptian"?

I'd say go ahead and merge once those are taken care of!

**Comment by jedwardwalters** [comment]
Thanks, @nathangibson!

**Comment by nathangibson** [comment]
I'm going to hit the hay, so I'll try to get back to any questions tomorrow. But it looks like you're good to go.

**Comment by jedwardwalters** [comment]
@nathangibson Okay, I took care of these. Thanks for looking them over.

**Comment by nathangibson** [comment]
@jedwardwalters You're welcome!

**Pull request merged**
