### PR TITLE
June 1

### PR DESCRIPTION
**Pull request by jsaintlauren**
please merge

### CODE REVIEW

**Comment by davidamichelson** [comment]
@jsaintlauren Sorry this is the only one I could not merge. I will try to do it quickly if not, I may need to do it next week.

**Comment by davidamichelson** [comment]
@jsaintlauren alas this looks complex on this one. I will need to work through them with you. Maybe on Wed afternoon? In the mean time make a new branch off of dev for your next work.

**Comment by jsaintlauren** [comment]
Ok!

On Friday, June 3, 2016, David Michelson <notifications@github.com> wrote:

> @jsaintlauren <https://github.com/jsaintlauren> alas this looks complex
> on this one. I will need to work through them with you. Maybe on Wed
> afternoon? In the mean time make a new branch off of dev for your next work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/srophe/srophe-app-data/pull/202#issuecomment-223691102>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEY0lDTor-VdByMzOVD8XYQMcnLocGhRks5qIJOJgaJpZM4IsghZ>
> .
>


-- 
Sent by my large poodle - please excuse typos

**Comment by davidamichelson** [comment]
Okay a couple of quick questions @jsaintlauren. Can you please confirm that you want to delete totally the following person URI's?

Removing data/persons/tei/saints/tei/2106.xml
Removing data/persons/tei/saints/tei/1999.xml
Removing data/persons/tei/saints/tei/1922.xml
Removing data/persons/tei/saints/tei/1746.xml
Removing data/persons/tei/saints/tei/1715.xml

**Comment by davidamichelson** [comment]
Then it looks like the other changes affect 

CONFLICT (content): Merge conflict in data/works/tei/894.xml
CONFLICT (content): Merge conflict in data/works/tei/893.xml
CONFLICT (content): Merge conflict in data/works/tei/892.xml
CONFLICT (content): Merge conflict in data/works/tei/857.xml
Auto-merging data/works/tei/741.xml
Auto-merging data/works/tei/270.xml
Auto-merging data/works/tei/2009.xml
CONFLICT (content): Merge conflict in data/works/tei/2009.xml
Auto-merging data/works/tei/1330.xml
CONFLICT (content): Merge conflict in data/persons/tei/saints/tei/1998.xml
CONFLICT (content): Merge conflict in data/persons/tei/saints/tei/1897.xml
 I will check these by hand as soon as I can.

**Pull request merged**
