### PR TITLE
Dls spear edits

### PR DESCRIPTION
**Pull request by dlschwartz**
Edits to Severus Letters 3004, 3012, 3031, 3046, 3052, 3054, 3055, 3039, 3029, 3075, 3115, 3127

### CODE REVIEW

**Comment by dlschwartz** [comment]
@davidamichelson, I think I just successfully made a branch, made edits to that branch over the last couple of days (committing them periodically), pushed the branch to GitHub, and then made a pull request within GitHub. Let me know if it looks like I've screwed anything up. Thanks

**Comment by davidamichelson** [comment]
@dlschwartz !!!! You did it and no merge conflict!!!

**Comment by davidamichelson** [comment]
@jsaintlauren Welcome him to club!

**Comment by dlschwartz** [comment]
: )

**Comment by jsaintlauren** [comment]
Bienvenue!

**Pull request merged**
