### PR TITLE
Updated bibl/author names and bibl/ptr in persons. #228

### PR DESCRIPTION
**Pull request by davidamichelson**
@wsalesky Please don't merge this yet. It looks good but with a couple caveats. 
1. Am I correct that this was run only on the persons/tei directory, not the saints/tei? It will need to be run on both.
2. Is there a way to view the entire diff file? Viewing it here online (see below): it says: 
"Sorry, we could not display the entire diff because too many files (768) changed." I would like to scroll through all of them. Can I do this in the command line?

### CODE REVIEW

**Comment by davidamichelson** [comment]
Okay, re: 2 above I figured out how to review the last commit in Git which gives me access to the same information essentially.

**Comment by wsalesky** [comment]
It was run on both persons/tei and persons/tei/saints/tei.

Looks like this is the command you can use to see all files changed:
git diff --name-only SHA1 SHA2

**Comment by davidamichelson** [comment]
Ah, okay, all of the persons/tei/saints/tei files were in the section that was cut off due to length. Let me check a bit more.

**Comment by davidamichelson** [comment]
@wsalesky Could you please pull these changes on the dev server? Thank you

**Pull request merged**
