### PR TITLE
Feb. 2 

### PR DESCRIPTION
**Pull request by jsaintlauren**
Please pull my edits

### CODE REVIEW

**Comment by davidamichelson** [comment]
@wsalesky Uh oh, looks like there is a merge conflict here. Can you help me? Thanks!

**Comment by wsalesky** [comment]
I will take a look.

**Comment by davidamichelson** [comment]
Thanks, if you can get me to the command line I can make the edits.

**Comment by wsalesky** [comment]
Hi Dave, 
There are instructions, if you click the link for "Use the command line"
Do you want to do it, or would you like me to do it? 
-Winona

**Comment by jsaintlauren** [comment]
Ugh I am sorry if I did something wrong!

**Comment by wsalesky** [comment]
@jsaintlauren I don't think you did not do anything wrong, occasional merge conflicts are a git occupational hazard.

**Comment by wsalesky** [comment]
@davidamichelson I see this is still not merged, would you like me to do the merge?

**Pull request closed without merging**
