### PR TITLE
Splitting records

### PR DESCRIPTION
**Pull request by davidamichelson**
Splitting records

### CODE REVIEW

**Comment by davidamichelson** [comment]
Files changed in this merge: 
M       data/persons/tei/10.xml
M       data/persons/tei/100.xml
M       data/persons/tei/1000.xml
M       data/persons/tei/1002.xml
M       data/persons/tei/1003.xml
M       data/persons/tei/1004.xml
M       data/persons/tei/1005.xml
M       data/persons/tei/1006.xml
M       data/persons/tei/1007.xml
M       data/persons/tei/1008.xml
M       data/persons/tei/1009.xml
M       data/persons/tei/101.xml
M       data/persons/tei/1010.xml
M       data/persons/tei/1011.xml
M       data/persons/tei/1012.xml
M       data/persons/tei/1013.xml
M       data/persons/tei/1014.xml
M       data/persons/tei/1015.xml
M       data/persons/tei/1016.xml
M       data/persons/tei/1017.xml
M       data/persons/tei/1018.xml
M       data/persons/tei/1019.xml

**Comment by davidamichelson** [comment]
Okay here are the files which this merge changes:
100644 100644 23e6a0d... b36f338... M  data/persons/tei/saints/tei/1370.xml
:100644 100644 02b7640... 9fa87dd... M  data/persons/tei/saints/tei/1418.xml
:100644 100644 26fbb25... 15e9f18... M  data/persons/tei/saints/tei/1483.xml
:100644 100644 f276a24... 5406eba... M  data/persons/tei/saints/tei/1705.xml
:100644 100644 9a19dbe... 5c98523... M  data/persons/tei/saints/tei/1956.xml
:100644 100644 a27d306... 33e4604... M  data/persons/tei/saints/tei/1958.xml
:100644 100644 1490e0c... 287a986... M  data/persons/tei/saints/tei/1990.xml
:100644 100644 5ba646d... 43cce68... M  data/persons/tei/saints/tei/2064.xml
:000000 100644 0000000... 0991499... A  data/persons/tei/saints/tei/3139.xml
:000000 100644 0000000... b35822e... A  data/persons/tei/saints/tei/3140.xml
:000000 100644 0000000... da04f5b... A  data/persons/tei/saints/tei/3141.xml
:000000 100644 0000000... 3c580a9... A  data/persons/tei/saints/tei/3142.xml
:000000 100644 0000000... 0d1ff0a... A  data/persons/tei/saints/tei/3143.xml
:000000 100644 0000000... 4109c92... A  data/persons/tei/saints/tei/3144.xml
:000000 100644 0000000... 500001a... A  data/persons/tei/saints/tei/3145.xml
:000000 100644 0000000... 4c20e1d... A  data/persons/tei/saints/tei/3146.xml
:000000 100644 0000000... 601effd... A  data/persons/tei/saints/tei/3147.xml
:000000 100644 0000000... e081469... A  data/persons/tei/saints/tei/3148.xml
:000000 100644 0000000... 84bb547... A  data/persons/tei/saints/tei/3149.xml
:000000 100644 0000000... 0b6cf8f... A  data/persons/tei/saints/tei/3150.xml
:000000 100644 0000000... a54a7ba... A  data/persons/tei/saints/tei/3151.xml
:000000 100644 0000000... 4e9bb1b... A  data/persons/tei/saints/tei/3152.xml

I will copy them manually to master branch after merging them to dev

**Comment by davidamichelson** [comment]
@wsalesky Okay, I merged these to dev. Just to confirm, the next thing I should do is move the files to master branch as well? Do I just copy these 22 files?

**Comment by wsalesky** [comment]
You should be able to merge the branch into master. Or you can manually move them.

**Pull request merged**
